Add up-to-date RUC LSM and surface diagnostics to the gsl/develop
ufs-community/MPAS-Model pull request #3
Opened 2024-03-29 20:06 UTC by tanyasmirnova

The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).

Enter a description of this PR. This should include why this PR was created, and what it does.
1. This PR adds RUC LSM to the physics package. 
2. The version of RUC LSM is updated to the latest used in RRFSv1
3. Updated 2-m diagnostics subroutine to add log-diagnostics for stable stratification

Testing and relations to other Pull Requests should be added as subsequent comments.

See the below examples for more information.
https://github.com/MPAS-Dev/MPAS/pull/930
https://github.com/MPAS-Dev/MPAS/pull/931

2024-03-29 20:35 UTC, tanyasmirnova commented
More details on commits: [9cc3f2c](https://github.com/NOAA-GSL/MPAS-Model/pull/3/commits/9cc3f2cb446020fa9a67030cf0f800d3f2d30519) and [af9d4b1](https://github.com/NOAA-GSL/MPAS-Model/pull/3/commits/af9d4b1224fb9c6ae36a1787a9db0b37618f44a3): they merge NSSL changes into src/tools/registry parse.c and gen_inc.c

2024-04-01 15:33 UTC, mdtoyNOAA approved these changes

2024-04-02 16:33 UTC, AndersJensen-NOAA requested changes

2024-04-02 16:33 UTC, AndersJensen-NOAA commented on src/core_atmosphere/physics/mpas_atmphys_constants.F
> + REAL(kind=RKIND), PARAMETER :: p1000mb      = 100000.    ! pressure at 1000 hPa (pa)
Remove `p1000mb` and use P0 defined above.

2024-04-02 16:33 UTC, AndersJensen-NOAA commented on src/core_atmosphere/physics/physics_wrf/module_sf_sfcdiags_ruclsm.F
> +!- saturation functions are from Thompson microphysics scheme
I will put these functions in a utilities module so they can imported and used. This is fine for now though.

2024-04-03 21:53 UTC, merged