Fixes to the the merge with MAPS 8.1
ufs-community/MPAS-Model pull request #8
Opened 2024-04-26 22:05 UTC by tanyasmirnova

The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).
Fixes to the the merge with MAPS 8.1
Enter a description of this PR. This should include why this PR was created, and what it does.
The 8.,1 version of MPAS has a new driver for sea ice which was using only Noah sea ice model. To fix the merge RUC ice model had to be added to the driver_seaice. 
Testing and relations to other Pull Requests should be added as subsequent comments.
The fixes are tested for the 24 feb 2023 case on jet: /mnt/lfs4/BMC/wrfruc/smirnova/MPAS_conus13_20230224_mpasGSL
See the below examples for more information.
https://github.com/MPAS-Dev/MPAS/pull/930
https://github.com/MPAS-Dev/MPAS/pull/931

2024-04-30 15:17 UTC, AndersJensen-NOAA requested changes

2024-04-30 15:17 UTC, AndersJensen-NOAA commented on src/core_atmosphere/physics/physics_wrf/module_sf_ruclsm.F
> +      if(doseaice) goto 119
Can you get rid of this goto?

2024-04-30 15:17 UTC, AndersJensen-NOAA commented on src/core_atmosphere/physics/physics_wrf/module_sf_ruclsm.F
> +     if (.not. doseaice) goto 119
Can you get rid of this goto?

2024-04-30 15:17 UTC, AndersJensen-NOAA commented on src/core_atmosphere/physics/physics_wrf/module_sf_ruclsm.F
> +     if (.not. doseaice) goto 119
And others below.

2024-04-30 18:02 UTC, joeolson42 commented on src/core_atmosphere/physics/physics_wrf/module_mp_thompson.F
how did this get removed? Is it intended? I suppose it doesn't matter with Anders' submodule...

2024-04-30 18:02 UTC, joeolson42 approved these changes

2024-05-01 19:14 UTC, jderrico-noaa commented on src/core_atmosphere/physics/physics_wrf/module_mp_thompson.F
@AndersJensen-NOAA does this matter?

2024-05-02 03:27 UTC, AndersJensen-NOAA commented
@jderrico-noaa @joeolson42 @tanyasmirnova This PR compiles and runs for a 3-km CONUS case (I just ran a short 3-h test). This can be merged. Note that we won't be using the deleted version of the microphysics, but it probably should be committed back so that our version of MPAS stays in line with the other versions out there.

2024-05-02 15:51 UTC, jderrico-noaa commented
@tanyasmirnova can you restore the deleted microphysics?  After that I'll merge this!

2024-05-02 15:58 UTC, tanyasmirnova commented
Janet,
I found a problem with soil moisture in this PR. I am looking at this
today, and hopefully will fix the problem towards the end of the day.
I can also restore the MP Thompson in physics_wrf.
Thanks,
Tanya

On Thu, May 2, 2024 at 9:52 AM Janet Derrico ***@***.***>
wrote:

> @tanyasmirnova <https://github.com/tanyasmirnova> can you restore the
> deleted microphysics? After that I'll merge this!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GSL/MPAS-Model/pull/8#issuecomment-2090865503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJHANACDXBKEMYV2GAUJTK3ZAJOKLAVCNFSM6AAAAABG3PNICCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJQHA3DKNJQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-02 23:42 UTC, tanyasmirnova commented
Janet and All,
First, about module_mp_thompson.F - it gets deleted automatically when the
Thompson submodule is checked out.
I haven't deleted it myself.

Second, at this point I think I want to give up on PR#8. I'll try to
explain briefly.
I noticed that after the second call to RUC LSM from driver_seaice, soil
moisture on land got corrupted. I am not quite sure why, but maybe the
reason is that the names of variables for land and ice are the same (in
RRFS the names are *_land and *_ice). When we get from MPAS a variable from
the driver_seaice, it should update only sea-ice points, but it appears
that land points are also modified or corrupted.
When I removed soil moisture from updated variables in driver_seaice,
then it looked good.
However, there are several other variables that are updated for sea ice
points, and cannot be removed. And now I am not sure they are not corrupted
over land.
Also, in the MPAS 8.1, 2-m diagnostics is called out of driver_seaice which
is called after driver_lsm, and I have suspicions that over the land it
will not be correct.
Because we have limited time for figuring all this out, I think we should
go with a simple solution #2: keep one call to RUC LSM from driver_lsm, and
also keep RUC 2-m diagnostics in driver_lsm. In this case we do not need to
call dirver_seaice from mpas_atmphys_driver.F with RUC LSM, and should add
IF around driver_seaice call.
This solution has less changes to the code, but most likely will not be
accepted by Laura Fowler.

I am running a test now with Solution #2. I will see the results tomorrow
morning. If I see more reasonable differences between 8.1 and 8.0 code, I
will make a new PR.
Let me know what you think about this.
Thank you,
Tanya

On Thu, May 2, 2024 at 9:56 AM Tanya Smirnova - NOAA Affiliate <
***@***.***> wrote:

> Janet,
> I found a problem with soil moisture in this PR. I am looking at this
> today, and hopefully will fix the problem towards the end of the day.
> I can also restore the MP Thompson in physics_wrf.
> Thanks,
> Tanya
>
> On Thu, May 2, 2024 at 9:52 AM Janet Derrico ***@***.***>
> wrote:
>
>> @tanyasmirnova <https://github.com/tanyasmirnova> can you restore the
>> deleted microphysics? After that I'll merge this!
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/NOAA-GSL/MPAS-Model/pull/8#issuecomment-2090865503>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AJHANACDXBKEMYV2GAUJTK3ZAJOKLAVCNFSM6AAAAABG3PNICCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJQHA3DKNJQGM>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-05-03 15:40 UTC, tanyasmirnova commented
@jderrico-noaa @AndersJensen-NOAA 
Janet and All,
The results look much more reasonable now with the Solution #2. 
I am going to submit the PR.
Anders, could you please repeat your 3-km case. 
In my 15-km CONUS test the 2-m temperature differences compared to 8.0 code looks like:
![Screenshot 2024-05-03 at 9 31 32 AM](https://github.com/NOAA-GSL/MPAS-Model/assets/38667904/31678d04-ef75-4628-96bb-7bb18934327f)
And for 2-m Qv:
![Screenshot 2024-05-03 at 9 32 23 AM](https://github.com/NOAA-GSL/MPAS-Model/assets/38667904/0c25beb4-dba4-4639-ba8a-e5cff3324764)
Top-level soil moisture looks like:
![Screenshot 2024-05-03 at 9 38 46 AM](https://github.com/NOAA-GSL/MPAS-Model/assets/38667904/0092ac68-67cc-433d-a465-39977a389a29)
The difference look much more reasonable than those shown at the Wednesday's meeting.

2024-05-03 16:13 UTC, tanyasmirnova commented
PR for solution 2 is submitted: https://github.com/NOAA-GSL/MPAS-Model/pull/9

2024-05-07 21:15 UTC, closed without merging